Lesson.H1.CsharpFeatures.WebApp/Models/ErrorViewModel.cs
using System;

namespace Lesson.H1.CsharpFeatures.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lesson.H1.CsharpFeatures.WebApp/ViewModels/FurnitureListViewModel.cs
using System;
using Lesson.H1.CsharpFeatures.Domain;
using System.Collections.Generic;

namespace Lesson.H1.CsharpFeatures.WebApp.ViewModels
{
    public class FurnitureListViewModel
    {
        public List<Furniture> Furnitures { get; set; }

        public int Count { get; set; }

        public string QuoteOfTheDay { get; set; }
    }
}

Lesson.H1.CsharpFeatures.WebApp/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lesson.H1.CsharpFeatures.WebApp.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Search(string searchkey)
        {
            return View(); //todo: create a view named “Search” under Views/Home }
        }
    }
}

Lesson.H1.CsharpFeatures.WebApp/Controllers/FurnitureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lesson.H1.CsharpFeatures.Domain;
using Lesson.H1.CsharpFeatures.WebApp.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lesson.H1.CsharpFeatures.WebApp.Controllers
{
    public class FurnitureController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "List of furniture";

            List<Furniture> furnitures = Furniture.GetAll();

            return View(furnitures);
        }

        public IActionResult Detail()
        {
            ViewData["Title"] = "Detail of furniture";

            List<Furniture> furnitures = Furniture.GetAll();

            FurnitureListViewModel furnitureViewModel = new FurnitureListViewModel
            {
                Furnitures = furnitures,
                Count = furnitures.Count,
                QuoteOfTheDay = "The best furniture in Town"
            };

            return View(furnitureViewModel);
        }


    }
}

Lesson.H1.CsharpFeatures.WebApp/Controllers/HomeController.cs
using Lesson.H1.CsharpFeatures.Domain;
using Lesson.H1.CsharpFeatures.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson.H1.CsharpFeatures.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Furniture> household = Furniture.GetAll();
            return View(household);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lesson.H1.CsharpFeatures.WebApp/Views/About/Index.cshtml
@{ 
    ViewData["Title"] = "Index";
} 

<h1>About</h1> 
<p>This is the about page, with tons of info...</p>

Lesson.H1.CsharpFeatures.WebApp/Views/About/Search_verkeerd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Thanks for searching.

Lesson.H1.CsharpFeatures.WebApp/Views/Furniture/Detail.cshtml
@using Lesson.H1.CsharpFeatures.Domain
@using Lesson.H1.CsharpFeatures.WebApp.ViewModels
@model FurnitureListViewModel



<ul>
    @{
        foreach(Furniture furniture in Model.Furnitures)
            {
                <li>
                    @furniture?.Type - @furniture?.Color<br/>
                    <i>@furniture?.Description</i>
                </li>
            }
    }

</ul>
<p>Total number of articles: @Model.Count</p>
<p>
    @Model.QuoteOfTheDay
</p>

Lesson.H1.CsharpFeatures.WebApp/Views/Furniture/Index.cshtml
@using Lesson.H1.CsharpFeatures.Domain
@model List<Furniture>


<ul>
@{
    foreach(Furniture furniture in Model)
            {
                <li>@furniture?.Type</li>
            }
}
</ul>

Lesson.H1.CsharpFeatures.WebApp/Views/Home/Index.cshtml
@using Lesson.H1.CsharpFeatures.Domain
@model List<Furniture>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <ul>
    @{
        foreach(Furniture furniture in Model)
        {
            <li>@furniture
            <p><img src="~/images/@(furniture.Id).png" width="200px" /></p>
            </li>
        }
    }
    </ul>


    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lesson.H1.CsharpFeatures.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson.H1.CsharpFeatures.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lesson.H1.CsharpFeatures.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Furniture" asp-action="Index">Furniture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lesson.H1.CsharpFeatures.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>